### ISSUE TITLE
How is the proper way to enable float printf?

### ISSUE THREAD

**Issue by jancotipsarevic** [stm32duino/CMake_workspace#1]
Hello I am using stm32duino+cmake+freertos+clion and so far I could say it is a great framework,  now I am stuck in a point that probably should be easy but I coudn´t find a solution (as a basic thing it could be great to be added to the examples or wiki) wich is how to add the compiler options to enable floating point using printf. 
I would really appreciate any help.
Thanks

this is a view what I have tried:

`include(build_sketch)

add_compile_options(--specs=nano.specs -u_printf_float) #FAIL
add_compile_options(-u_printf_float) #FAIL

build_sketch(TARGET "n_f401re_tft"
    SOURCES`

**Comment by jancotipsarevic** [comment]
Same thing trying to get USB CDC working , so basically is to find a way to configure the common parametters normally done when starting a project using arduino ide but using cmake instead let say, USB support, Optimize, C Runtime Library.

I will really appreciate any help.

**Comment by massonal** [comment]
Hi,

I think the functions you need here are a combination of [set_board](https://github.com/stm32duino/Arduino_Core_STM32/wiki/Functions-reference#set_board) and  [overall_settings](https://github.com/stm32duino/Arduino_Core_STM32/wiki/Functions-reference#overall_settings).

You can look up the examples in this repo to get an usage overview, or the wiki (linked here) for a fuller reference.
Example with [2_Helloworld](https://github.com/stm32duino/CMake_workspace/blob/main/sketchbook/2_Helloworld/CMakeLists.txt):

```cmake
# STEP 2: configure the build
# -----------------------------------------------------------------------------

include(set_board)
set_board("NUCLEO_L433RC_P"
  # SERIAL generic
  # USB none
  # XUSB FS
  # VIRTIO disabled
  # BOOTLOADER dfuo / dfu2 / hid
)

include(overall_settings)
overall_settings(
  # STANDARD_LIBC
  # PRINTF_FLOAT
  # SCANF_FLOAT
  # DEBUG_SYMBOLS
  # LTO
  # NO_RELATIVE_MACRO
  # UNDEF_NDEBUG
  # OPTIMIZATION "s"
  # BUILD_OPT ./build.opt
  # DISABLE_HAL_MODULES ADC I2C RTC SPI TIM DAC EXTI ETH SD QSPI
  # CORE_CALLBACK
)
```

Features that do not depend on the targeted STM32, such as the support for floats, belong in `overall_settings`. Others belong in `set_board`.


Let me know if this explanation solves your issues!

**Comment by jancotipsarevic** [comment]
Excellent, right to the point, now all my issues are solved. I started my test from the Blink example and this project has a very minimalist CMakeLists file, if I were started from this Helloworld example I wouldn't had any problem sorry for that.
Thank you very much.
