### ISSUE TITLE
Starting from 4_DumpFile.ino example but using STM32duino_STM32SD instead SD fails

### ISSUE THREAD

**Issue by jancotipsarevic** [stm32duino/CMake_workspace#2]
Hello, I need to deal with a SD card but using STM32duino_STM32SD libray instead the arduino one (SD) as I need SDIO instead SPI.
I have tried with the CMakeLists.txt as in the DumpFile example changing the entries to STM32duino_STM32SD in place of SD but it looks it is far from that simple thing. Please do you have any example or hint?
Thank you very much.

**Comment by massonal** [comment]
Hello,

What kind of error do you get? Can you share the CMake sample you wrote so far?

--------------------

Keep in mind that, when using external libraries, you need to do two things:
- reference the library with `exernal_library()`
- use the library in your project when calling `build_sketch()`

The "tricky" point with STM32SD is its dependency chain:

> (your sketch) -> STM32SD -> FatFS

So you have *two* external libraries to handle, actually.
Note that downloading libraries them is not supported in CMake, you have to do it yourself. (The advantage of this is, you can put them wherever you want 😉)

The CMake snippet you end up with should look like the following:
```cmake
# STEP 3: configure your sketch
# -----------------------------------------------------------------------------
include(external_library)
# I cannot tell the dependencies of the library ahead-of-time
# Please write them in using the DEPENDS ... clause
external_library(PATH "${USER_LIBS}/FatFs")
external_library(PATH "${USER_LIBS}/STM32SD" DEPENDS FatFs)

include(build_sketch)
build_sketch(TARGET "4_DumpFile"
  SOURCES
  4_DumpFile.ino

  DEPENDS
  STM32SD
)
```

**Comment by jancotipsarevic** [comment]
Thank you for your help. Finally I have it working but I have to add the FatFs sources as at compilation some "undefined references" errors appeared (related to FatFs sources), here you are my CMakeLists.txt. 

**CMakeLists.txt:**

cmake_minimum_required(VERSION 3.21)

file(REAL_PATH "C:/Organizations/stm32duino/FEATHER_BSP/Arduino_Core_STM32" CORE_PATH EXPAND_TILDE)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "C:/Organizations/stm32duino/FEATHER_BSP/libraries" USER_LIBS EXPAND_TILDE)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

set(Python3_EXECUTABLE "C:/Organizations/stm32duino/FEATHER_BSP/venv/Scripts/python.exe")

project("feather_bsp_project")

include(set_board)
set_board("FEATHER_F405"
        # SERIAL generic
        # USB none
        USB CDCgen
        XUSB FS
        # VIRTIO disabled
        # BOOTLOADER dfuo / dfu2 / hid
        )

include(overall_settings)
overall_settings(
        # STANDARD_LIBC
        PRINTF_FLOAT
        # SCANF_FLOAT
        # DEBUG_SYMBOLS
        # LTO
        # NO_RELATIVE_MACRO
        # UNDEF_NDEBUG
        # OPTIMIZATION "s"
        # BUILD_OPT ./build.opt
        # DISABLE_HAL_MODULES ADC I2C RTC SPI TIM DAC EXTI ETH SD QSPI
        # CORE_CALLBACK
)

set(FREERTOS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/STM32FreeRTOS")
set(DRIVERS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/drivers")
set(FATFS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/libraries/FatFs")
set(STM32SD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/libraries/STM32duino_STM32SD")

include_directories(
        .
        EXT_BOARDS
        ${DRIVERS_DIR}/include
        ${FREERTOS_DIR}/src
        ${FREERTOS_DIR}/src/FreeRTOS
        ${FREERTOS_DIR}/src/FreeRTOS/Source/include
        ${FREERTOS_DIR}/portable/CMSIS_RTOS
        ${FREERTOS_DIR}/portable/GCC/ARM_CM4F
        ${FATFS_DIR}/src
        ${FATFS_DIR}/src/drivers
        ${STM32SD_DIR}/src
)

FILE(GLOB FATFS_SOURCES
        ${FATFS_DIR}/src/*.c
        ${FATFS_DIR}/src/drivers/*.c
        ${FATFS_DIR}/src/option/*.c
        )

FILE(GLOB STM32SD_SOURCES
        ${STM32SD_DIR}/src/*.c
        ${STM32SD_DIR}/src/*.cpp
        )

FILE(GLOB FREERTOS_SOURCES
        ${FREERTOS_DIR}/src/FreeRTOS/Source/*.c
        ${FREERTOS_DIR}/src/*.c
        )

FILE(GLOB DRIVERS_SOURCES
        ${DRIVERS_DIR}/src/*.cpp
        )

include(external_library)
external_library(PATH "${USER_LIBS}/FatFs")
external_library(PATH "${USER_LIBS}/STM32duino_STM32SD" DEPENDS FatFs)

include(build_sketch)
build_sketch(TARGET "feather_bsp"
    SOURCES
    Datalogger.cpp
    ${FATFS_SOURCES}
    #${STM32SD_SOURCES}
    ${DRIVERS_SOURCES}
    ${FREERTOS_SOURCES}
    DEPENDS
    Wire
    SPI
    STM32duino_STM32SD
)

**Comment by massonal** [comment]
Hey, I'm glad to hear it works now!

I suspect there was something fishy in "${USER_LIBS}/STM32SD/CMakeLists.txt" that made the linker look for a static library. You re-downloading the library (now it's "STM32duino_STM32SD") cleared it and forced the CMakeLists.txt to be regenerated from scratch.

For you information, you can force overriding a library's CMakeLists.txt with the "FORCE" argument ;)

> I have to add the FatFs sources as at compilation some "undefined references" errors appeared (related to FatFs sources)

I'm confused regarding this, it shouldn't be necessary... I see it's commented in the code you shared: do you still need it? If yes, I will definitely spend some time understanding why, if it's a bug in the CMake framework or the library itself 🤔

**Comment by jancotipsarevic** [comment]
Yes, the naming is confusing for me, using the Arduino IDE, when you download the STM32SD library it is under STM32duino_STM32SD directory, but if you install the Arduino one it is in SD directory, so I think I am not re-dowloading anything as in my project only the STM32duino_STM32SD is present and it looks STM32duino_STM32SD is the proper way to call it.

If you look carefully my CMakeLists.txt it is commented the STM32SD_SOURCES but the FATFS_SOURCES is present and in my case needed.

Thank you very much.

**Comment by massonal** [comment]
Regarding the library names, keep in mind [the following](https://github.com/stm32duino/STM32SD#stm32-sd-library-for-arduino):

> This library is for SD card slots connected to the SDIO-/SDMMC-hardware of the processor. For slots connected to SPI-hardware use the standard Arduino SD library.
> 
> This library follow Arduino API.
> 
> For more information about it, please visit: http://www.arduino.cc/en/Reference/SD

There are two SD libraries: "SD", maintained by Arduino, working over SPI, and "STM23SD", maintained by stm32duino, working over SDMMC.

Still, it looks like you used STM23SD all along, yet the folder name changed 🤷 I don't know what you did, yet it makes things work, so, great!

Since your project works now, I'll be closing this thread. Do not hesitate to re-open it, or open another issue, should the need arise.

🚀 !
