### ISSUE TITLE
problem using STM32Ethernet and LwIP under cmake

### ISSUE THREAD

**Issue by jancotipsarevic** [stm32duino/CMake_workspace#3]
Hello all, I am trying to compile the DhcpChatServer example for the NUCLEO-F429ZI using cmake. I have tried using CLion and STM32CubeIde with same effect. I am using a simple way to reach all code in my CMakeLists.txt file but the next compilation issue appears:

`CMakeFiles/n_429zi_bsp.dir/STM32Ethernet/src/EthernetClient.cpp.o -c C:/Organizations/stm32duino/N_F429ZI_BSP/STM32Ethernet/src/EthernetClient.cpp
In file included from C:/Organizations/stm32duino/N_F429ZI_BSP/STM32Ethernet/src/Dhcp.h:7,
                 from C:/Organizations/stm32duino/N_F429ZI_BSP/STM32Ethernet/src/STM32Ethernet.h:8,
                 from C:/Organizations/stm32duino/N_F429ZI_BSP/STM32Ethernet/src/EthernetClient.cpp:7:
C:/Organizations/stm32duino/N_F429ZI_BSP/STM32Ethernet/src/EthernetUdp.h:47:32: error: expected class-name before '{' token
   47 | class EthernetUDP : public UDP {
      |                                ^
C:/Organizations/stm32duino/N_F429ZI_BSP/STM32Ethernet/src/EthernetUdp.h:84:18: error: type 'Print' is not a base type for type 'EthernetUDP'
   84 |     using Print::write;
      |                  ^~~~~`

Here it is my CMakeLists.txt file:

`cmake_minimum_required(VERSION 3.21)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project("N_F429ZI_BSP_Project")

include(set_board)
set_board("NUCLEO_F429ZI"
        # SERIAL generic
        # USB none CDCgen
        # USB CDCgen
        # XUSB FS
        # VIRTIO disabled
        # BOOTLOADER dfuo / dfu2 / hid
        )

include(overall_settings)
overall_settings(
        # STANDARD_LIBC
        PRINTF_FLOAT
        # SCANF_FLOAT
        # DEBUG_SYMBOLS
        # LTO
        # NO_RELATIVE_MACRO
        # UNDEF_NDEBUG
        # OPTIMIZATION "s"
        # BUILD_OPT ./build.opt
        # DISABLE_HAL_MODULES ADC I2C RTC SPI TIM DAC EXTI ETH SD QSPI
        # CORE_CALLBACK
)

set(FREERTOS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/STM32FreeRTOS")
set(FREERTOS_PLUS_CLI_DIR "${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS-Plus-CLI")
set(DRIVERS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/drivers")
set(LWIP_DIR "${CMAKE_CURRENT_SOURCE_DIR}/LwIP/src")
set(ETH_DIR "${CMAKE_CURRENT_SOURCE_DIR}/STM32Ethernet/src")

include_directories(
        .
        EXT_BOARDS
        ${DRIVERS_DIR}/include
        ${FREERTOS_DIR}/src
        ${FREERTOS_DIR}/src/FreeRTOS
        ${FREERTOS_DIR}/src/FreeRTOS/Source/include
        ${FREERTOS_DIR}/portable/CMSIS_RTOS
        ${FREERTOS_DIR}/portable/GCC/ARM_CM4F
        ${FREERTOS_PLUS_CLI_DIR}/
        ${LWIP_DIR}/
        ${LWIP_DIR}/arch
        ${LWIP_DIR}/compat/posix
        ${LWIP_DIR}/compat/posix/arpa
        ${LWIP_DIR}/compat/posix/net
        ${LWIP_DIR}/compat/posix/sys
        ${LWIP_DIR}/compat/stdc
        ${LWIP_DIR}/lwip
        ${LWIP_DIR}/lwip/apps
        ${LWIP_DIR}/lwip/priv
        ${LWIP_DIR}/lwip/prot
        ${LWIP_DIR}/netif
        ${LWIP_DIR}/netif/ppp
        ${LWIP_DIR}/netif/ppp/polarssl
        ${ETH_DIR}/
        ${ETH_DIR}/utility
)

FILE(GLOB FREERTOS_SOURCES
        ${FREERTOS_DIR}/src/FreeRTOS/Source/*.c
        ${FREERTOS_DIR}/src/*.c
        )

FILE(GLOB FREERTOS_PLUS_SOURCES
        ${FREERTOS_PLUS_CLI_DIR}/*.c
        )

FILE(GLOB DRIVERS_SOURCES
        ${DRIVERS_DIR}/src/*.cpp
        )

FILE(GLOB LWIP_SOURCES
        ${LWIP_DIR}/api/*.c
        ${LWIP_DIR}/core/*.c
        ${LWIP_DIR}/core/ipv4/*.c
        ${LWIP_DIR}/core/ipv6/*.c
        ${LWIP_DIR}/netif/*.c
        ${LWIP_DIR}/netif/ppp/*.c
        ${LWIP_DIR}/netif/ppp/polarssl/*.c
        ${LWIP_DIR}/system/OS/*.c
        )

FILE(GLOB ETH_SOURCES
        ${ETH_DIR}/*.cpp
        ${ETH_DIR}/utility/*.cpp
        )

include(build_sketch)
build_sketch(TARGET "n_429zi_bsp"
    SOURCES
    DhcpChatServer.cpp

    ${DRIVERS_SOURCES}
    ${FREERTOS_SOURCES}
    ${FREERTOS_PLUS_SOURCES}
    ${LWIP_SOURCES}
    ${ETH_SOURCES}

    DEPENDS
    Wire
    SPI
)

NOTE:All libraries are the latest version as long as stm32duino.

I don´t know if the libraries have something that crashes the cmake flow. Anyone tried to compile those libraries using cmake?, if yes could you provide an example.

Thank you very much

**Comment by massonal** [comment]
Hello @jancotipsarevic,
Thanks for reporting this issue. I think you need to study this example [4_DumpFile](https://github.com/stm32duino/CMake_workspace/tree/main/sketchbook/4_DumpFile); It explains how to deal with Arduino libraries.

You cannot just add the library sources to your sketch's... Instead, you should use [`external_library()`](https://github.com/stm32duino/Arduino_Core_STM32/wiki/Functions-reference#external_library). This function generates a CMakeLists.txt tuned for the library so that you can refer to it in `build_sketch()`'s DEPENDS clause.

You should follow a similar pattern with LwIP - I guess you're using [that](https://github.com/stm32duino/LwIP) implementation?


```cmake
include(external_library)
external_library(
    PATH ${LWIP_DIR} # LWIP_DIR point to the root of the library, not .../src
)
external_library(
    PATH ${ETH_DIR} # same consideration here
    DEPENDS LwIP
)

include(build_sketch)
build_sketch(TARGET "n_429zi_bsp"
    SOURCES
    DhcpChatServer.cpp
    ${DRIVERS_SOURCES}
    ${FREERTOS_SOURCES}
    ${FREERTOS_PLUS_SOURCES}
    DEPENDS
    Wire SPI STM32Ethernet
)
```

Please let me know whether this solves your issues!
Best regards,
@massonal

**Comment by jancotipsarevic** [comment]
Hello Alexis, thank you for your quick response, I have implemented the
changes you suggested, the compilation fails with that error:

====================[ Build | n_429zi_bsp | Debug
]=============================
"C:\Program Files\JetBrains\CLion 2022.3.2\bin\cmake\win\x64\bin\cmake.exe"
--build C:\Organizations\stm32duino\N_F429ZI_BSP\cmake-build-debug --target
n_429zi_bsp -j 12
[1/350] Building C object
LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ethip6.c.o
FAILED: LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ethip6.c.o
C:\PROGRA~2\ARMGNU~1\12DBAB~1.2RE\bin\AR19DD~1.EXE -DARDUINO_ARCH_STM32
-DARDUINO_NUCLEO_F429ZI -DBOARD_ID=NUCLEO_F429ZI
-DBOARD_NAME=\"NUCLEO_F429ZI\" -DNDEBUG -DSTM32F4xx -DUSE_FULL_LL_DRIVER
-DVARIANT_H=\"variant_NUCLEO_F429ZI.h\"
--IC:/Organizations/stm32duino/N_F429ZI_BSP/Arduino_Core_STM32/cmake/../variants/STM32F4xx/F427Z(G-I)T_F429ZET_F429Z(G-I)(T-Y)_F437Z(G-I)T_F439Z(G-I)(T-Y)
-g -fdiagnostics-color=always -mthumb --param max-inline-insns-single=500
-ffunction-sections -fdata-sections
-fmacro-prefix-map=C:/Organizations/stm32duino/N_F429ZI_BSP/LwIP=. -Os
-DSTM32F429xx -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mcpu=cortex-m4
-DHAL_UART_MODULE_ENABLED -std=gnu17 -MD -MT
LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ethip6.c.o -MF
LwIP\CMakeFiles\LwIP_bin.dir\src\core\ipv6\ethip6.c.o.d -o
LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ethip6.c.o -c
C:/Organizations/stm32duino/N_F429ZI_BSP/LwIP/src/core/ipv6/ethip6.c
In file included from
C:/Organizations/stm32duino/N_F429ZI_BSP/LwIP/src/core/ipv6/ethip6.c:42:
C:/Organizations/stm32duino/N_F429ZI_BSP/LwIP/src/lwip/opt.h:51:10: fatal
error: lwipopts.h: No such file or directory
   51 | #include "lwipopts.h"
      |          ^~~~~~~~~~~~
compilation terminated.

Here is the CMakeLists.txt:

cmake_minimum_required(VERSION 3.21)

# STEP 1: set up bases of environment
# -----------------------------------------------------------------------------

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

# To support python virtual environment
set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project("N_F429ZI_BSP_Project")

# STEP 2: configure the build
# -----------------------------------------------------------------------------

include(set_board)
set_board("NUCLEO_F429ZI"
        # SERIAL generic
        # USB none CDCgen
        # USB CDCgen
        # XUSB FS
        # VIRTIO disabled
        # BOOTLOADER dfuo / dfu2 / hid
        )

include(overall_settings)
overall_settings(
        # STANDARD_LIBC
        PRINTF_FLOAT
        # SCANF_FLOAT
        # DEBUG_SYMBOLS
        # LTO
        # NO_RELATIVE_MACRO
        # UNDEF_NDEBUG
        # OPTIMIZATION "s"
        # BUILD_OPT ./build.opt
        # DISABLE_HAL_MODULES ADC I2C RTC SPI TIM DAC EXTI ETH SD QSPI
        # CORE_CALLBACK
)

set(FREERTOS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/STM32FreeRTOS")
set(FREERTOS_PLUS_CLI_DIR "${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS-Plus-CLI")
set(DRIVERS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/drivers")
set(LWIP_DIR "${CMAKE_CURRENT_SOURCE_DIR}/LwIP")
set(ETH_DIR "${CMAKE_CURRENT_SOURCE_DIR}/STM32Ethernet")
#set(LWIP_DIR "${CMAKE_CURRENT_SOURCE_DIR}/LwIP/src")
#set(ETH_DIR "${CMAKE_CURRENT_SOURCE_DIR}/STM32Ethernet/src")

include_directories(
        .
        EXT_BOARDS
        ${DRIVERS_DIR}/include
        ${FREERTOS_DIR}/src
        ${FREERTOS_DIR}/src/FreeRTOS
        ${FREERTOS_DIR}/src/FreeRTOS/Source/include
        ${FREERTOS_DIR}/portable/CMSIS_RTOS
        ${FREERTOS_DIR}/portable/GCC/ARM_CM4F
        ${FREERTOS_PLUS_CLI_DIR}/
#        ${LWIP_DIR}
#        ${LWIP_DIR}/arch
#        ${LWIP_DIR}/compat/posix
#        ${LWIP_DIR}/compat/posix/arpa
#        ${LWIP_DIR}/compat/posix/net
#        ${LWIP_DIR}/compat/posix/sys
#        ${LWIP_DIR}/compat/stdc
#        ${LWIP_DIR}/lwip
#        ${LWIP_DIR}/lwip/apps
#        ${LWIP_DIR}/lwip/priv
#        ${LWIP_DIR}/lwip/prot
#        ${LWIP_DIR}/netif
#        ${LWIP_DIR}/netif/ppp
#        ${LWIP_DIR}/netif/ppp/polarssl
#        ${ETH_DIR}
#        ${ETH_DIR}/utility
)

FILE(GLOB FREERTOS_SOURCES
        ${FREERTOS_DIR}/src/FreeRTOS/Source/*.c
        ${FREERTOS_DIR}/src/*.c
        )

FILE(GLOB FREERTOS_PLUS_SOURCES
        ${FREERTOS_PLUS_CLI_DIR}/*.c
        )

FILE(GLOB DRIVERS_SOURCES
        ${DRIVERS_DIR}/src/*.cpp
        )

#FILE(GLOB LWIP_SOURCES
#        ${LWIP_DIR}/api/*.c
#        ${LWIP_DIR}/core/*.c
#        ${LWIP_DIR}/core/ipv4/*.c
#        ${LWIP_DIR}/core/ipv6/*.c
#        ${LWIP_DIR}/netif/*.c
#        ${LWIP_DIR}/netif/ppp/*.c
#        ${LWIP_DIR}/netif/ppp/polarssl/*.c
#        ${LWIP_DIR}/system/OS/*.c
#        )
#
#FILE(GLOB ETH_SOURCES
#        ${ETH_DIR}/*.cpp
#        ${ETH_DIR}/utility/*.cpp
#        )

include(external_library)
external_library(
        PATH ${LWIP_DIR} # LWIP_DIR point to the root of the library,
not .../src
)
external_library(
        PATH ${ETH_DIR} # same consideration here
        DEPENDS LwIP
)

include(build_sketch)
build_sketch(TARGET "n_429zi_bsp"
    SOURCES
    DhcpChatServer.cpp

    ${DRIVERS_SOURCES}
    ${FREERTOS_SOURCES}
    ${FREERTOS_PLUS_SOURCES}
#    ${LWIP_SOURCES}
#    ${ETH_SOURCES}

    DEPENDS
    Wire
    SPI
    STM32Ethernet

)

#target_link_options(n_429zi_bsp PRIVATE "LINKER:--no-warn-rwx-segments")

Thank you very much for your help.

Regards

**Comment by jancotipsarevic** [comment]
Hello Alexis, to make it clearer I have removed unnecessary elements. I
followed closely the 4_DumpFile example. I also put LwIP and
STM32Ethernet under libraries directory.
The compilation fails with that error:

====================[ Build | n_429zi_bsp | Debug
]=============================
"C:\Program Files\JetBrains\CLion 2022.3.2\bin\cmake\win\x64\bin\cmake.exe"
--build C:\Organizations\stm32duino\N_F429ZI_BSP\cmake-build-debug --target
n_429zi_bsp -j 12
[1/332] Building C object
LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ip6_frag.c.o
FAILED: LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ip6_frag.c.o
C:\PROGRA~2\ARMGNU~1\12DBAB~1.2RE\bin\AR19DD~1.EXE -DARDUINO_ARCH_STM32
-DARDUINO_NUCLEO_F429ZI -DBOARD_ID=NUCLEO_F429ZI
-DBOARD_NAME=\"NUCLEO_F429ZI\" -DNDEBUG -DSTM32F4xx -DUSE_FULL_LL_DRIVER
-DVARIANT_H=\"variant_NUCLEO_F429ZI.h\"
-IC:/Organizations/stm32duino/N_F429ZI_BSP/Arduino_Core_STM32/cmake/../variants/STM32F4xx/F427Z(G-I)T_F429ZET_F429Z(G-I)(T-Y)_F437Z(G-I)T_F439Z(G-I)(T-Y)
-g -fdiagnostics-color=always -mthumb --param max-inline-insns-single=500
-ffunction-sections -fdata-sections
-fmacro-prefix-map=C:/Organizations/stm32duino/N_F429ZI_BSP/libraries/LwIP=.
-Os -DSTM32F429xx -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mcpu=cortex-m4
-DHAL_UART_MODULE_ENABLED -std=gnu17 -MD -MT
LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ip6_frag.c.o -MF
LwIP\CMakeFiles\LwIP_bin.dir\src\core\ipv6\ip6_frag.c.o.d -o
LwIP/CMakeFiles/LwIP_bin.dir/src/core/ipv6/ip6_frag.c.o -c
C:/Organizations/stm32duino/N_F429ZI_BSP/libraries/LwIP/src/core/ipv6/ip6_frag.c
In file included from
C:/Organizations/stm32duino/N_F429ZI_BSP/libraries/LwIP/src/core/ipv6/ip6_frag.c:42:
C:/Organizations/stm32duino/N_F429ZI_BSP/libraries/LwIP/src/lwip/opt.h:51:10:
fatal error: lwipopts.h: No such file or directory
   51 | #include "lwipopts.h"


This is the final CMakeLists.txt file.

cmake_minimum_required(VERSION 3.21)

# STEP 1: set up bases of environment
# -----------------------------------------------------------------------------

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

# To support python virtual environment
set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project("N_F429ZI_BSP_Project")

# STEP 2: configure the build
# -----------------------------------------------------------------------------

include(set_board)
set_board("NUCLEO_F429ZI")

include(overall_settings)
overall_settings()

include(external_library)
external_library(
        PATH "${USER_LIBS}/LwIP" # LWIP_DIR point to the root of the
library, not .../src
)
external_library(
        PATH "${USER_LIBS}/STM32Ethernet" # same consideration here
        DEPENDS LwIP
)

include(build_sketch)
build_sketch(TARGET "n_429zi_bsp"
    SOURCES
    DhcpChatServer.cpp

    DEPENDS
    STM32Ethernet
)


Thank you very much for your help.

Regards

**Comment by massonal** [comment]
The issue you're having now, as I understand it:

__STM32Ethernet depends on LwIP__ (#include some of its headers).
LwIP must be configured through a header lwipopts.h, to be usually written by the user application.
In the current case, however, that configuration file is part of STM32Ethernet.
This means that, in a sense, __LwIP depends on STM32Ethernet__.

This kind of circular dependency can't be easily describe through CMake tagets.
The easiest way for you to solve this is to add STM32Ethernet/src as a global include directory (`include_directories()` call).
The clean way would be to look up the generated CMakeLists.txt in LwIP and STM32Ethernet and edit LwIP's "bin" target to reference STM32Ethernet's source tree as include directory.

Hope this helps!

**Comment by massonal** [comment]
@fpistm This circular dependency is an unusual use case.
How/ Do you think it should be handled? 
- Adding a dedicated example or wiki entry,
- or shipping STM32Ethernet / LwIP with a working CMakeLists.txt,
- or changing the target generator to cover such cases in their general algorithm?
- or yet something else?

**Comment by fpistm** [comment]
> This circular dependency is an unusual use case.

I guess STM32SD and FatFS has the same issue.
STM32Ethernet library uses the LWiP and so provide the configuration same for STM32SD FatFS.

What is the best one from your point of view?

**Comment by jancotipsarevic** [comment]
Alexis right to the point, excellent!! , now works, here you have my
CMakeLists.txt:

cmake_minimum_required(VERSION 3.21)

# STEP 1: set up bases of environment
# -----------------------------------------------------------------------------

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

# To support python virtual environment
set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project("N_F429ZI_BSP_Project")

# STEP 2: configure the build
# -----------------------------------------------------------------------------

include(set_board)
set_board("NUCLEO_F429ZI"
        SERIAL generic
)

include(overall_settings)
overall_settings()

include_directories(
        .
        ${USER_LIBS}/STM32Ethernet/src
)

include(external_library)
external_library(
        PATH "${USER_LIBS}/LwIP"
)
external_library(
        PATH "${USER_LIBS}/STM32Ethernet"
        DEPENDS LwIP
)

include(build_sketch)
build_sketch(TARGET "n_429zi_bsp"
    SOURCES
    DhcpChatServer.cpp

    DEPENDS
    STM32Ethernet
)


Thank you very much.

Regards

**Comment by jancotipsarevic** [comment]
Adding include_directories solved the problem.

include_directories(
        .
        ${USER_LIBS}/STM32Ethernet/src
)
