### ISSUE TITLE
Support for TFT_eSPI library

### ISSUE THREAD

**Issue by jancotipsarevic** [stm32duino/CMake_workspace#4]
Hello all, I am trying to test TFT_eSPI library under cmake for a new project with no success. It looks like this libray does not fit properly with stm32duino cmake definitions or version. If it is reasonable, please, it could be great to count on one example setting this library.
Any way here it is my CMakeLists.txt file to support it and the error that appear.

cmake_minimum_required(VERSION 3.21)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project(N_F401RE_TFT_eSPI) # Project Name

set(BOARDNAME "NUCLEO_F401RE")

include(set_board)
set_board("${BOARDNAME}"
        SERIAL generic
)

include_directories(
        .
        ${USER_LIBS}/TFT_eSPI
        ${USER_LIBS}/TFT_eSPI/Extensions
        ${USER_LIBS}/TFT_eSPI/Fonts
        ${USER_LIBS}/TFT_eSPI/Fonts/Custom
        ${USER_LIBS}/TFT_eSPI/Fonts/GFXFF
        ${USER_LIBS}/TFT_eSPI/Processors
        ${USER_LIBS}/TFT_eSPI/TFT_Drivers
        ${USER_LIBS}/TFT_eSPI/User_Setups
)

FILE(GLOB TFT_ESPI_SOURCES
        ${USER_LIBS}/TFT_eSPI/*.cpp
        ${USER_LIBS}/TFT_eSPI/Extensions/*.cpp
        ${USER_LIBS}/TFT_eSPI/Fonts/*.c
        ${USER_LIBS}/TFT_eSPI/Processors/*.c
        )

include(external_library)
external_library(
        PATH "${USER_LIBS}/TFT_eSPI"
        DEPENDS SPI
)

include(build_sketch)
build_sketch(TARGET ${PROJECT_NAME}
    SOURCES
    tft_espi_test.cpp
    ${TFT_ESPI_SOURCES}
    DEPENDS
    SPI
)

#Error in configuration

-- The ASM compiler identification is GNU
-- Found assembler: C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 rel1/bin/arm-none-eabi-gcc.exe
CMake Error at libraries/TFT_eSPI/CMakeLists.txt:2 (idf_component_register):
  Unknown CMake command "idf_component_register".

-- Configuring incomplete, errors occurred!
See also "C:/Organizations/stm32duino/N_F401RE_BSP/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "C:/Organizations/stm32duino/N_F401RE_BSP/cmake-build-debug/CMakeFiles/CMakeError.log".

**Comment by massonal** [comment]
Hello @jancotipsarevic,

I assume you're trying to work with [this specific library](https://github.com/Bodmer/TFT_eSPI).
As you can see, it is delivered with a CMakeLists.txt already, wich contains
```cmake

idf_component_register(SRCS "TFT_eSPI.cpp"
                    INCLUDE_DIRS "."
                    PRIV_REQUIRES arduino)
```

As there is a CMakeLists.txt already, by default, the call to `external_library()` in your CMakeLists.txt does not override it. You can force overriding with the `FORCE` keyword; cf. [the function's documentation](https://github.com/stm32duino/Arduino_Core_STM32/wiki/Functions-reference#external_library)

In addition, the CMakeLists.txt built into TFT_eSPI looks like it is part of a larger project and can't be used alone. That's why you get the error you reported in your comment.

I suggest:
- you use the `FORCE` keyword in your CMakeLists.txt to override the library's CMakeLists.txt;
- you open an issue in TFT_eSPI's repo asking for details on how to use their CMakeLists.txt and/or asking for their implementation to support stm32duino's framework. Feel free to @ me there then, I can take part in that discussion ;)

Best regards & best wishes for the new year!

**Comment by massonal** [comment]
Also --try with this CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.21)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project(N_F401RE_TFT_eSPI) # Project Name

set(BOARDNAME "NUCLEO_F401RE")

include(set_board)
set_board("${BOARDNAME}"
	SERIAL generic
)

# Not sure what this is for... Probably can be deleted?
# Arduino IDE does no such thing, why should CMake?
include_directories(
	.
	${USER_LIBS}/TFT_eSPI
	${USER_LIBS}/TFT_eSPI/Extensions
	${USER_LIBS}/TFT_eSPI/Fonts
	${USER_LIBS}/TFT_eSPI/Fonts/Custom
	${USER_LIBS}/TFT_eSPI/Fonts/GFXFF
	${USER_LIBS}/TFT_eSPI/Processors
	${USER_LIBS}/TFT_eSPI/TFT_Drivers
	${USER_LIBS}/TFT_eSPI/User_Setups
)

include(external_library)
external_library(
	PATH "${USER_LIBS}/TFT_eSPI"
	DEPENDS SPI
)

include(build_sketch)
build_sketch(TARGET N_F401RE_TFT_eSPI
	SOURCES
	tft_espi_test.cpp
	DEPENDS
	TFT_eSPI
)
```

I just fixed some dependencies ordering & removed unnecessary calls. Otherwise you'll run into other issues later.

**Comment by jancotipsarevic** [comment]
Thank you Alexis, same error after the changes you proposed (also using
FORCE), I will contact the library owner.
Thank you for your help.

CMake Error at libraries/TFT_eSPI/CMakeLists.txt:2 (idf_component_register):
Unknown CMake command "idf_component_register".

cmake_minimum_required(VERSION 3.21)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Arduino_Core_STM32" CORE_PATH)
file(TO_CMAKE_PATH "${CORE_PATH}" CORE_PATH)

file(REAL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/libraries" USER_LIBS)
file(TO_CMAKE_PATH "${USER_LIBS}" USER_LIBS)

list(APPEND CMAKE_MODULE_PATH ${CORE_PATH}/cmake)
set(CMAKE_TOOLCHAIN_FILE toolchain)

set(Python3_EXECUTABLE "${CMAKE_CURRENT_SOURCE_DIR}/venv/Scripts/python.exe")

project(N_F401RE_TFT_eSPI) # Project Name

set(BOARDNAME "NUCLEO_F401RE")

include(set_board)
set_board("${BOARDNAME}"
	SERIAL generic
)

# Not sure what this is for... Probably can be deleted?
# Arduino IDE does no such thing, why should CMake?
# include_directories(
#	.
#	${USER_LIBS}/TFT_eSPI
#	${USER_LIBS}/TFT_eSPI/Extensions
#	${USER_LIBS}/TFT_eSPI/Fonts
#	${USER_LIBS}/TFT_eSPI/Fonts/Custom
#	${USER_LIBS}/TFT_eSPI/Fonts/GFXFF
#	${USER_LIBS}/TFT_eSPI/Processors
#	${USER_LIBS}/TFT_eSPI/TFT_Drivers
#	${USER_LIBS}/TFT_eSPI/User_Setups
#)

include(external_library)
external_library(
	PATH "${USER_LIBS}/TFT_eSPI"
	DEPENDS SPI
        FORCE
)

include(build_sketch)
build_sketch(TARGET N_F401RE_TFT_eSPI
	SOURCES
	tft_espi_test.cpp
	DEPENDS
	TFT_eSPI
)
